### ISSUE TITLE
Empty responses

### ISSUE THREAD

**Issue by IrealiTY** [GeekyDeaks/discord-destinybot#14]
Using the d!manifest command to check if bot is working, succeeds.
Using the d!stats <psn> results in no reply.

**Comment by IrealiTY** [comment]
Weird restarting the bot three times solved it... but still got these errors, are they normal responses?

```
2016-08-21T18:56:18.731Z - debug: got message from [Saeris] in channel [test]:  d!manifest
2016-08-21T18:56:18.732Z - debug: found command 'manifest'
2016-08-21T18:56:18.732Z - debug: executing command [manifest] with args []
2016-08-21T18:56:18.910Z - debug: issuing destiny API cmd: https://www.bungie.net/Platform/Destiny/Manifest/
2016-08-21T18:56:19.307Z - debug: response code 200
2016-08-21T18:56:19.308Z - debug: ErrorCode: 1, ThrottleSeconds: 0, ErrorStatus: Success, Message: Ok
2016-08-21T18:56:19.308Z - debug: No Language Flag entered or invaild language option specifed.
2016-08-21T18:56:19.308Z - debug: Defaulting to config option: en
```

**Comment by unisys12** [comment]
Looks normal to me. What did the `d!stats` response look like?

**Comment by GeekyDeaks** [comment]
Hi Aleks - yeah, sorry should have explained, the master branch is in a state of flux right now as we are trying to work out the best way to sync the bungie manifest DB to the bot, but the `d!stats` and `d!summary` should still be working ok.  There is another branch for the current VOC bot, which is stable if you want to take a look at that, but the structure is quite a bit different, so I'd probably still recommend working on this one for new features as all the old commands should be migrated in a few days time.

**Comment by GeekyDeaks** [comment]
I just remembered.  The `master` branch is using mongodb now.  It might behave erratically if it's not setup.  I'll check.  I also don't recommend switching between branches in the same local repo as the `config.js` has changed significantly enough to cause headaches.  I'd suggest pulling the repo twice into two separate directories and doing a `git checkout voc` in one of them...

**Comment by GeekyDeaks** [comment]
Ok, `master` is now very close to stable - and should remain that way in future, but it needs the README updating to explaining the new config and mongoDB dependency for the destiny lookups.

**Comment by IrealiTY** [comment]
Cool cool - Ive been running the version I had since 2 days ago with no further issues - looks like if it suddenly stops working restarting the bot is a way to make it work again. No weirdness in the log tho.

I'll wait for your README update to update my own instance

**Comment by GeekyDeaks** [comment]
Ah ok - so we have noticed that `discord.js` can throw an uncaught exception on certain network issues and crash the bot.  Our current workaround is to install pm2 and use that to keep the bot alive.

i.e.

```
sudo npm install pm2 -g
pm2 start destinybot.js
```

I am new to node, but from what I can gather, this is the preferred approach to unexpected errors, but if you have any other ideas please let us know!

**Comment by GeekyDeaks** [comment]
Hi Aleks, I have pushed a new README to explain a little of the new scheme and how to install.  The main thing is that you will need to review the `config.js` carefully as the location of certain parameters has changed like the bungie API_KEY.  All persistence now relies upon mongoDB too, so you may need to install a local instance.

Let us know how you get on.

**Comment by GeekyDeaks** [comment]
Is it ok for me to close this one now?

**Comment by IrealiTY** [comment]
Yep ;) Let me do that for you
