### ISSUE TITLE
Adopt Discord Standard Command Entry Format

### ISSUE THREAD

**Issue by unisys12** [GeekyDeaks/discord-destinybot#4]
Currently, commands have to be entered like so:
`/dsummary <username>`

To be more friendly across multiple systems/servers, bot should assume the standard format for entering commands, which is:
`/d summary <username>`

**Note:** The _space_ after the bot alias is really just a preference, but is pretty much become a standard across all bots. Took me a few minutes to figure out that's how the commands had to be entered, but I am no expert either. LOL! Totally open for debate of course.

**Comment by GeekyDeaks** [comment]
Yup - that needs fixing!  Should be pretty easy though.

**Comment by GeekyDeaks** [comment]
I think the fix works as intended, but I'll leave the issue open just in case.

**Comment by unisys12** [comment]
Seems to be working just fine on my end after your changes. Started working on this once I entered the issue, but got side tracked with _adulting_. Sorry about that.
